### PR TITLE
Return local IP when proxy IP detection fails

### LINKED ISSUE #3: Failure to detect a proxy IP results in none
Our production infrastructure includes a load balancer, so we use`$clientIp->proxy()` to enable the original IP address of the user.

However, in development there is no LB so proxy IP detection fails. Due to [this condition](https://github.com/middlewares/client-ip/blob/728e89e771245668e9047392109672664564e2e4/src/ClientIp.php#L129-L133), if no IP is detected during the loop, then a `void` return is used.

The solution is simple, add this to the end of the method:

```php
return $ip;
```

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #3

### CODE REVIEW

File: src/ClientIp.php [hunk 1]
```diff
@@ -107,33 +107,70 @@ public function process(ServerRequestInterface $request, DelegateInterface $dele
...
 
-        $ip = null;
-        $server = $request->getServerParams();
-
-        if (!empty($server['REMOTE_ADDR']) && self::isValid($server['REMOTE_ADDR'])) {
-            $ip = $server['REMOTE_ADDR'];
+        if ($ip = $this->getLocalIp($request)) {
+            if (!in_array($ip, $this->proxyIps)) {
+                return $ip;
+            }
```
Comment (shadowhand) [inline src/ClientIp.php]: I refactored this because it was really hard for me to follow as written. Functionality remains the same, with better separation of concerns.

**Comment by shadowhand** [comment]
Scrutinizer liked my changes. 😎

File: src/ClientIp.php (hunk 1 above)
Comment (oscarotero) [reply src/ClientIp.php]: I think the functionality does not remain the same. The logic should be:
* Get the ip using the default way (`REMOTE_ADDR`). Let's call it `$localIp`
* If proxies hasn't been configured returns `$localIp`
* If there's an array of allowed proxy ips, check if `$localIp` is in this array. If it's not, returns `$localIp`.
* Get the new ip using the proxy headers and return it if it's found, or `$localIp` if doesn't.

In this refactoring `$this->proxyIps` is used to check the ip returned by `$this->getProxyIp()`, it should used to check the ip returned by `$this->getLocalIp()`

**Review by oscarotero — CHANGES_REQUESTED** [review]

File: src/ClientIp.php (hunk 1 above)
Comment (shadowhand) [reply src/ClientIp.php]: Ah, it makes sense now. The purpose of `proxyIps` was a bit confusing. Will update.

Comment (oscarotero) [reply src/ClientIp.php]: Feel free to improve readme for a better understanding of proxyIps functionality.

Comment (shadowhand) [reply src/ClientIp.php]: Okay, still a bit confused. Shouldn't the choices be:

1. If remote IP detection is enabled, attempt to return remote IP address.
2. If proxy headers are enabled, attempt to return proxied IP address.
3. If local IP address is found:
   - If proxy IPs are defined, and the local IP is in the proxy list, void the local IP.
   - Otherwise return the local IP.

Comment (oscarotero) [reply src/ClientIp.php]: You may want to configure the proxies with or without ips. No ips means you're trusting in all proxies, so just try to get the ip from headers and use the remote_addr as fallback. Obviously, this less secure. Setting an array of ips of well known proxies, get the ip only from any of these proxies, and use remote_addr as fallback too.

Comment (shadowhand) [reply src/ClientIp.php]: I think the current changes follow the correct order.

Comment (shadowhand) [reply src/ClientIp.php]: Ah, there's a subtle difference that I missed that the tests are not accounting for:

The local IP **has** to be checked against proxy IPs if the proxy IP list is defined. Otherwise something weird is happening. Got it.

File: src/ClientIp.php [hunk 2]
```diff
@@ -107,33 +107,78 @@ public function process(ServerRequestInterface $request, DelegateInterface $dele
...
+        $proxiedIp = $this->getProxiedIp($request);
+
+        if (!empty($proxiedIp)) {
+            // Found IP address via proxy-defined headers.
+            return $proxiedIp;
         }
 
-        foreach ($this->proxyHeaders as $name) {
-            if ($request->hasHeader($name) && ($ip = self::getHeaderIp($request->getHeaderLine($name))) !== null) {
+        return $localIp;
```
Comment (shadowhand) [inline src/ClientIp.php:132]: @oscarotero okay, functionality should be a match with existing code. Verify for me?

Comment (oscarotero) [reply src/ClientIp.php:132]: seems good to me

**Review by oscarotero — APPROVED** [review]

**Comment by shadowhand** [comment]
Released in v0.5.0.

**Comment by oscarotero** [comment]
Well, this is a bugfix, so it could be released as 0.4.1. And the link to compare this version with the previous in changelog is missing.
anyway, now it's done.

**Comment by shadowhand** [comment]
@oscarotero 🤦‍♂️ good point on the version. I updated the changelog to include the compare link.
